### ISSUE TITLE
GitHub Sponsor Listing

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/Community#24]
We've got a listing of "Additional Sponsors" who have sponsored Blockchain Commons through the "Sponsor" page. It's here: https://www.blockchaincommons.com/sponsors.html

It'd be nice if that was automated, and even nicer if it was attractively laid out with GitHub user names and icons.

Here's an example of someone who's done that:
https://karabiner-elements.pqrs.org/

They appear to be doing so in JavaScript code, which suggests there's either a library or an API. 

This short project would be to update our Sponsors page ( https://github.com/BlockchainCommons/www.blockchaincommons.com/blob/master/sponsors.md ), replacing the "Additional Sponsors" section with an automated, graphical display like this.

**Comment by HarshCasper** [comment]
Hi @shannona 

I did not request it to be assigned to me, but I went ahead and played around with the same to see if I can do a simple POC. And I'm glad, I was able to complete it up. 

I have made use of an unofficial API here: https://sponsors.trnck.dev/ 

Furthermore, with the aid of some JavaScript Client-Side scripting, I am able to fetch JSON data over the API and parse it to render it on HTML. The end result looks something like this:

![image](https://user-images.githubusercontent.com/47351025/122878043-e6edf480-d354-11eb-98dd-e9273e76d504.png)

As of now, I need to see how we can embed it on the Jekyll site that we have in place. One Stack Overflow answer suggested, to create a `assets` directory and place the script over there and then embed the HTML portion over the Markdown that we have. 

Can you please suggest the way forward and if possible can I take up this project since the POC part is pretty much done here.

**Comment by shannona** [comment]
Wow, that's terrific.

Embedding it is definitely the next step. This would be the location, replacing the current textual list under "Additional Sponsors":

https://www.blockchaincommons.com/sponsors.html

So, yes, please go ahead and try it out by creating the assets directory and replacing that text on the sponsors page.

It's all stored here:
https://github.com/BlockchainCommons/www.blockchaincommons.com

If you have any questions or need any support, just let me know, otherwise flag me when it's ready to merge and we can see how it works!

**Comment by HarshCasper** [comment]
Hi @shannona 

Here is the final work. Can you share some feedback before I send in a Pull Request for it to get merged, or does it look all good?

![Tab-1624473106488](https://user-images.githubusercontent.com/47351025/123150131-a3dc7000-d47f-11eb-8175-5999dbabdf1e.gif)

**Comment by shannona** [comment]
That looks amazing! Do the names/pictures link through to the GitHub profile for the user? That'd be my preference. In any case, yes, please release that.

**Comment by HarshCasper** [comment]
Hi @shannona 

Here is the PR: https://github.com/BlockchainCommons/www.blockchaincommons.com/pull/17 

Yes, the names and the avatars link to their GitHub profile.

**Comment by shannona** [comment]
We've installed this, then had it stop working due to loss of the online server that supported it. I've since replaced it with a simple but attractive bit of HTML for putting in users as we see fit.
